when:
  - event: [push, pull_request]

steps:
  backend_lint:
    image: golangci/golangci-lint:v2.10.1-alpine
    commands:
      - cd backend
      - golangci-lint run ./...

  backend_test:
    image: golang:1.25-alpine
    commands:
      - cd backend
      - go test ./...

  backend_build:
    image: golang:1.25-alpine
    commands:
      - cd backend
      - go build ./cmd/app

  frontend_check:
    image: node:22-alpine
    commands:
      - cd frontend
      - corepack enable
      - corepack prepare pnpm@10.8.1 --activate
      - pnpm config set store-dir /tmp/pnpm-store
      - CI=true pnpm install --frozen-lockfile
      - cp src/lib/server/backend.example.ts src/lib/server/backend.ts || true
      - cp src/lib/server/set-cookie.example.ts src/lib/server/set-cookie.ts || true
      - pnpm check

  frontend_build:
    image: node:22-alpine
    commands:
      - cd frontend
      - corepack enable
      - corepack prepare pnpm@10.8.1 --activate
      - pnpm config set store-dir /tmp/pnpm-store
      - CI=true pnpm install --frozen-lockfile
      - cp src/lib/server/backend.example.ts src/lib/server/backend.ts || true
      - cp src/lib/server/set-cookie.example.ts src/lib/server/set-cookie.ts || true
      - pnpm build
