version: "2"

run:
  timeout: 3m
  tests: true

# Keep it intentionally low-noise but aligned with Google Go Style Guide themes:
# - naming, comments, and error string style
# - common correctness checks
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - unused
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# Exclude generated/vendor-ish things if you add them later.
# (No exclude paths for now to avoid hiding real issues.)
