package facilitysql
package facilitysql




























































}	}, nil		TotalPages: domain.CalculateTotalPages(total, params.Limit),		Page:       params.Page,		Total:      total,		Items:      items,	return &domain.PaginatedList[domainFacility.AlarmDefinition]{	}		return nil, err	if err := db.Limit(params.Limit).Offset(offset).Order("name ASC").Find(&items).Error; err != nil {	offset := (params.Page - 1) * params.Limit	}		return nil, err	if err := db.Count(&total).Error; err != nil {	}		db = db.Where("name ILIKE ? OR alarm_note ILIKE ?", "%"+params.Search+"%", "%"+params.Search+"%")	if params.Search != "" {	db := r.db.Model(&domainFacility.AlarmDefinition{})	var total int64	var items []domainFacility.AlarmDefinitionfunc (r *alarmDefinitionRepo) GetPaginatedList(params domain.PaginationParams) (*domain.PaginatedList[domainFacility.AlarmDefinition], error) {}	return r.db.Delete(&domainFacility.AlarmDefinition{}, ids).Errorfunc (r *alarmDefinitionRepo) DeleteByIds(ids []uuid.UUID) error {}	return r.db.Save(entity).Errorfunc (r *alarmDefinitionRepo) Update(entity *domainFacility.AlarmDefinition) error {}	return r.db.Create(entity).Errorfunc (r *alarmDefinitionRepo) Create(entity *domainFacility.AlarmDefinition) error {}	return items, err	err := r.db.Where("id IN ?", ids).Find(&items).Error	var items []*domainFacility.AlarmDefinitionfunc (r *alarmDefinitionRepo) GetByIds(ids []uuid.UUID) ([]*domainFacility.AlarmDefinition, error) {}	return &alarmDefinitionRepo{db: db}func NewAlarmDefinitionRepository(db *gorm.DB) domainFacility.AlarmDefinitionRepository {}	db *gorm.DBtype alarmDefinitionRepo struct {)	"gorm.io/gorm"	"github.com/google/uuid"	domainFacility "github.com/besart951/go_infra_link/backend/internal/domain/facility"	"github.com/besart951/go_infra_link/backend/internal/domain"import (